### ISSUE TITLE
in large view on card click, always the second card pulsates

### ISSUE THREAD

**Issue by MarHai** [codeformunich/FinderApp#45]
when in large view (cards on right-hand side) and clicking through the cards, the correct markers are highlighted but the wrong card (always the second from the top).

chrome 39, win 8.1

**Comment by bastiRe** [comment]
Hmm, somehow I can't replicate this behaviour. So if you're clicking on a card the correct node get's selected but instead of the clicked card the second one is highlighted?

**Comment by MarHai** [comment]
Cannot replicate it on another pc either (win7/chrome). However, I'll check later and  come back to you.

**Comment by MarHai** [comment]
okay, reproducable only in touch mode. i am working on a win8.1 machine with touchscreen - using the mouse does what is expected; using fingers does what I just described.

I'd close it for now, if that's okay? :)

**Comment by bastiRe** [comment]
Interesting. Have you tried with other browser in touch mode on Windows 8.1? I just checked on an iPad and everything works alright there.

**Comment by MarHai** [comment]
Just checked. It's a win8.1/chrome/touch-only combination.
