### ISSUE TITLE
Build experimental FinderApp variant with Ionic?  

### ISSUE THREAD

**Issue by saerdnaer** [codeformunich/FinderApp#52]
Should we test if it make sense to build a version of the FinderApp with http://ionicframework.com/ ?
Looks like this framework is more popular then the web starter kit…

At least it would be nice to have an informed opinion to this topic till the Hackaton on the weekend.

**Comment by bastiRe** [comment]
I don't think that it really makes sense.
Ionic is made to build hybrid mobile apps that should end up in the app store. That does not fit with the idea behind the finder app. The original idea was to have an easily accessible responsive web app for finding certain utilities. We don't want to flood the app stores with finder-clones.
Additionally, all the major features are already implemented in the current app. I'd much rather create one polished app than start from scratch again.
